[tool.poetry]
name = "tegaki-qr-helper"
version = "0.1.0"
description = ""
authors = ["kk-shinoda <koki.snd6@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
